import React from 'react';
import { ModuleDefinitionSchema } from './module.schema';
import { z } from 'zod';

/**
 * Page Factory
 * Dynamically yields React components for a generated module.
 * Instead of writing bespoke tables, this reads the Module Definition's `listViews`
 * and mounts the Universal DataTable.
 */
export class DynamicPageFactory {
  
  static generateListView(moduleDef: z.infer<typeof ModuleDefinitionSchema>, entityName: string) {
    const listViewConfig = moduleDef.listViews?.find(v => v.entity === entityName);
    
    if (!listViewConfig) {
      return <div>No List View Configuration found for {entityName}</div>;
    }

    // Returns a React Component that automatically renders a DataTable
    // wired to the `/api/v1/[module]/[entity]` endpoint.
    return function GeneratedListView() {
      return (
        <div className="p-8 space-y-4">
          <h1 className="text-2xl font-bold uppercase tracking-tight">{entityName} List</h1>
          <p className="text-muted-foreground text-sm">Automatically generated by the DP Media Enterprise Generator.</p>
          
          <div className="border rounded-md p-4 bg-card">
            {/* 
              This would normally mount the actual DataTable:
              <DataTable endpoint={\`/api/v1/\${moduleDef.id}/\${entityName}\`} columns={listViewConfig.columns} /> 
            */}
            <pre className="text-xs text-muted-foreground">
              [DataTable Mounted via Generator]
              Columns: {listViewConfig.columns.map(c => c.label).join(', ')}
            </pre>
          </div>
        </div>
      );
    };
  }
}
