import { QueueCertificationService, CertificationResult } from '../certification/QueueCertificationService';
import { MetricsCollector } from '../parity/MetricsCollector';

export class ExecutiveDashboard {
  public static generateReport(certResult: CertificationResult): string {
    const metrics = MetricsCollector.getSystemMetrics();
    const history = MetricsCollector.getHistory();
    const parityMatches = history.filter(h => h.matched).length;
    const parityPercent = history.length > 0 ? ((parityMatches / history.length) * 100).toFixed(2) : '100.00';

    const reliabilityScore = certResult.overallRecommendation === 'GO' ? 100 : 
      (certResult.state === 'WARNING' ? 85 : 40);
    
    const readinessScore = certResult.burnInPassed && certResult.exactlyOncePassed ? 100 : 50;

    return `
# Executive Parity Dashboard & Production Certification Report

## 1. Certification Status
**State:** ${certResult.state}
**Overall Recommendation:** ${certResult.overallRecommendation}

**Enterprise Readiness Score:** ${readinessScore}/100
**Reliability Score:** ${reliabilityScore}/100

## 2. Parity & System Metrics
**Global Parity Match:** ${parityPercent}% (${parityMatches}/${history.length} jobs)
**CPU Load:** ${metrics.cpu.toFixed(1)}%
**Memory Usage:** ${metrics.memory.toFixed(1)}MB
**Redis Latency:** ${metrics.redisLatencyMs.toFixed(2)}ms
**Database Latency:** ${metrics.dbLatencyMs.toFixed(2)}ms

## 3. Burn-In Validation
**Status:** ${certResult.burnInPassed ? '✅ PASSED' : '❌ FAILED'}
${certResult.burnInReasons.length > 0 ? certResult.burnInReasons.map(r => `- ${r}`).join('\n') : '- All burn-in thresholds satisfied.'}

## 4. Exactly-Once Verification
**Status:** ${certResult.exactlyOncePassed ? '✅ PASSED' : '❌ FAILED'}
${certResult.exactlyOnceReasons.length > 0 ? certResult.exactlyOnceReasons.map(r => `- ${r}`).join('\n') : '- Zero duplicate enqueues, executions, or completions detected.'}

## 5. Queue Drift Detection
**Severity:** ${certResult.driftSeverity}
${certResult.driftReasons.length > 0 ? certResult.driftReasons.map(r => `- ${r}`).join('\n') : '- No significant queue drift detected.'}

---
*Generated by Enterprise Validation Layer (Phase 3D).*
`;
  }
}
